# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Fiser33/iOSTiledViewerSpec.git'
platform :ios, '10.0'

target 'MZK_iOS' do
use_frameworks!
pod 'iOSTiledViewer', :git => 'https://github.com/moravianlibrary/iOSTiledViewer.git', :branch => 'master'
pod 'AFNetworking', '~> 2.0'
pod 'Google/Analytics'
pod 'TTTAttributedLabel'
pod 'Alamofire', '~> 4.4'
pod 'AlamofireObjectMapper', '~> 4.0'
pod 'ObjectMapper', '~> 2.2'
pod 'SWXMLHash', '~> 4.0.0'
pod 'RMessage'
end

