INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('abr', 'Abridger', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('acp', 'Art copyist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('act', 'Actor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('adi', 'Art director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('adp', 'Adapter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aft', 'Author of afterword, colophon, etc.', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('anl', 'Analyst', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('anm', 'Animator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ann', 'Annotator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ant', 'Bibliographic antecedent', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ape', 'Appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('apl', 'Appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('app', 'Applicant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aqt', 'Author in quotations or text abstracts', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('arc', 'Architect', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ard', 'Artistic director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('arr', 'Arranger', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('art', 'Artist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('asg', 'Assignee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('asn', 'Associated name', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ato', 'Autographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('att', 'Attributed name', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('auc', 'Auctioneer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aud', 'Author of dialog', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aui', 'Author of introduction, etc.', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aus', 'Screenwriter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aut', 'Author', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bdd', 'Binding designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bjd', 'Bookjacket designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bkd', 'Book designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bkp', 'Book producer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('blw', 'Blurb writer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bnd', 'Binder', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bpd', 'Bookplate designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('brd', 'Broadcaster', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('brl', 'Braille embosser', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bsl', 'Bookseller', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cas', 'Caster', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ccp', 'Conceptor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('chr', 'Choreographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('-clb', 'Collaborator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cli', 'Client', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cll', 'Calligrapher', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('clr', 'Colorist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('clt', 'Collotyper', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmm', 'Commentator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmp', 'Composer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmt', 'Compositor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cnd', 'Conductor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cng', 'Cinematographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cns', 'Censor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('coe', 'Contestant-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('col', 'Collector', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('com', 'Compiler', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('con', 'Conservator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cor', 'Collection registrar', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cos', 'Contestant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cot', 'Contestant-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cou', 'Court governed', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cov', 'Cover designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpc', 'Copyright claimant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpe', 'Complainant-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cph', 'Copyright holder', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpl', 'Complainant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpt', 'Complainant-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cre', 'Creator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('crp', 'Correspondent', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('crr', 'Corrector', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('crt', 'Court reporter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('csl', 'Consultant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('csp', 'Consultant to a project', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cst', 'Costume designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctb', 'Contributor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cte', 'Contestee-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctg', 'Cartographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctr', 'Contractor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cts', 'Contestee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctt', 'Contestee-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cur', 'Curator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cwt', 'Commentator for written text', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dbp', 'Distribution place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dfd', 'Defendant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dfe', 'Defendant-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dft', 'Defendant-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dgg', 'Degree granting institution', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dgs', 'Degree supervisor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dis', 'Dissertant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dln', 'Delineator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dnc', 'Dancer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dnr', 'Donor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dpc', 'Depicted', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dpt', 'Depositor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('drm', 'Draftsman', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('drt', 'Director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dsr', 'Designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dst', 'Distributor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dtc', 'Data contributor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dte', 'Dedicatee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dtm', 'Data manager', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dto', 'Dedicator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dub', 'Dubious author', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('edc', 'Editor of compilation', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('edm', 'Editor of moving image work', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('edt', 'Editor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('egr', 'Engraver', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('elg', 'Electrician', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('elt', 'Electrotyper', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('eng', 'Engineer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('enj', 'Enacting jurisdiction', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('etr', 'Etcher', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('evp', 'Event place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('exp', 'Expert', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fac', 'Facsimilist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fds', 'Film distributor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fld', 'Field director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('flm', 'Film editor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fmd', 'Film director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fmk', 'Filmmaker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fmo', 'Former owner', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fmp', 'Film producer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fnd', 'Funder', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fpy', 'First party', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('frg', 'Forger', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('gis', 'Geographic information specialist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('-grt', 'Graphic technician', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('his', 'Host institution', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('hnr', 'Honoree', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('hst', 'Host', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ill', 'Illustrator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ilu', 'Illuminator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ins', 'Inscriber', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('inv', 'Inventor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('isb', 'Issuing body', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('itr', 'Instrumentalist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ive', 'Interviewee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ivr', 'Interviewer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('jud', 'Judge', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('jug', 'Jurisdiction governed', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lbr', 'Laboratory', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lbt', 'Librettist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ldr', 'Laboratory director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('led', 'Lead', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lee', 'Libelee-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lel', 'Libelee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('len', 'Lender', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('let', 'Libelee-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lgd', 'Lighting designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lie', 'Libelant-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lil', 'Libelant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lit', 'Libelant-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lsa', 'Landscape architect', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lse', 'Licensee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lso', 'Licensor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ltg', 'Lithographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lyr', 'Lyricist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mcp', 'Music copyist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mdc', 'Metadata contact', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('med', 'Medium', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mfp', 'Manufacture place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mfr', 'Manufacturer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mod', 'Moderator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mon', 'Monitor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mrb', 'Marbler', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mrk', 'Markup editor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('msd', 'Musical director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mte', 'Metal-engraver', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mtk', 'Minute taker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mus', 'Musician', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('nrt', 'Narrator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('opn', 'Opponent', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('org', 'Originator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('orm', 'Organizer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('osp', 'Onscreen presenter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('oth', 'Other', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('own', 'Owner', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pan', 'Panelist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pat', 'Patron', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pbd', 'Publishing director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pbl', 'Publisher', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pdr', 'Project director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pfr', 'Proofreader', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pht', 'Photographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('plt', 'Platemaker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pma', 'Permitting agency', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pmn', 'Production manager', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pop', 'Printer of plates', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ppm', 'Papermaker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ppt', 'Puppeteer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pra', 'Praeses', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prc', 'Process contact', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prd', 'Production personnel', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pre', 'Presenter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prf', 'Performer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prg', 'Programmer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prm', 'Printmaker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prn', 'Production company', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pro', 'Producer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prp', 'Production place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prs', 'Production designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prt', 'Printer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prv', 'Provider', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pta', 'Patent applicant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pte', 'Plaintiff-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ptf', 'Plaintiff', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pth', 'Patent holder', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ptt', 'Plaintiff-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pup', 'Publication place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rbr', 'Rubricator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rcd', 'Recordist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rce', 'Recording engineer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rcp', 'Addressee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rdd', 'Radio director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('red', 'Redaktor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ren', 'Renderer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('res', 'Researcher', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rev', 'Reviewer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rpc', 'Radio producer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rps', 'Repository', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rpt', 'Reporter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rpy', 'Responsible party', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rse', 'Respondent-appellee', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rsg', 'Restager', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rsp', 'Respondent', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rsr', 'Restorationist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rst', 'Respondent-appellant', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rth', 'Research team head', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rtm', 'Research team member', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sad', 'Scientific advisor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sce', 'Scenarist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('scl', 'Sculptor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('scr', 'Scribe', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sds', 'Sound designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sec', 'Secretary', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sgd', 'Stage director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sgn', 'Signer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sht', 'Supporting host', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sll', 'Seller', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sng', 'Singer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('spk', 'Speaker', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('spn', 'Sponsor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('spy', 'Second party', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('srv', 'Surveyor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('std', 'Set designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stg', 'Setting', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stl', 'Storyteller', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stm', 'Stage manager', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stn', 'Standards body', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('str', 'Stereotyper', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tcd', 'Technical director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tch', 'Teacher', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ths', 'Thesis advisor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tld', 'Television director', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tlp', 'Television producer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('trc', 'Transcriber', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('trl', 'Translator', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tyd', 'Type designer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tyg', 'Typographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('uvp', 'University place', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('vac', 'Voice actor', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('vdg', 'Videographer', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('-voc', 'Vocalist', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wac', 'Writer of added commentary', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wal', 'Writer of added lyrics', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wam', 'Writer of accompanying material', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wat', 'Writer of added text', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wdc', 'Woodcutter', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wde', 'Wood engraver', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('win', 'Writer of introduction', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wit', 'Witness', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wpr', 'Writer of preface', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wst', 'Writer of supplementary textual content', 'en');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('act', 'Herec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('adp', 'Autor adaptace, upravovatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aft', 'Autor doslovu, tiráže atd.', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ann', 'Anotátor, autor rukopisných poznámek', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ant', 'Bibliografický předchůdce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('app', 'Žadatel, uchazeč', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aqt', 'Autor citací nebo úryvků textu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('arc', 'Architekt', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('arr', 'Autor aranžmá', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('art', 'Umělec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('asg', 'Nabyvatel autorského práva', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('asn', 'Přidružené jméno', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('att', 'Připisované jméno', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('auc', 'Licitátor, vyvolávač', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aud', 'Autor dialogů', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aui', 'Autor úvodu atd.', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aus', 'Autor filmového scénáře atd.', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('aut', 'Autor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bdd', 'Výtvarník vazby', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bjd', 'Autor obálky', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bkd', 'Knižní grafik', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bkp', 'Výrobce knihy', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bnd', 'Vazač', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bpd', 'Autor exlibris', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('bsl', 'Knihkupec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ccp', 'Autor koncepce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('chr', 'Choreograf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('clb', 'Spolupracovník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cli', 'Klient', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cll', 'Kaligraf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('clt', 'Kolotypér', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmm', 'Autor komentáře', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmp', 'Skladatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cmt', 'Sazeč', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cnd', 'Dirigent', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cns', 'Cenzor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('coe', 'Odpůrce odvolatele', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('col', 'Sběratel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('com', 'Sestavovatel, kompilátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cos', 'Odpůrce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cot', 'Odpůrce v odvolacím řízení, odvolatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cov', 'Výtvarník desky knihy nebo ochranného pouzdra pro dokument', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpc', 'Žadatel o udělení autorského práva', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpe', 'Žalobce jako odpůrce odvolatele v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cph', 'Nositel autorského práva', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpl', 'Žalobce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cpt', 'Žalobce jako odvolávající se strana v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cre', 'Tvůrce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('crp', 'Korespondent', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('crr', 'Korektor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('csl', 'Konzultant', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('csp', 'Konzultant projektu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cst', 'Návrhář kostýmů', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctb', 'Přispěvatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cte', 'Obhájce jako odpůrce odvolatele v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctg', 'Kartograf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctr', 'Kontrahent, smluvní partner', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cts', 'Obhájce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ctt', 'Obhájce jako odvolávající se strana v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cur', 'Kurátor výstavy', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('cwt', 'Autor komentáře textu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dfd', 'Obžalovaný', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dfe', 'Obžalovaný jako odpůrce odvolatele v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dft', 'Obžalovaný jako odvolávající se strana v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dgg', 'Udélovatel akademické hodnosti', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dis', 'Autor diplomové práce nebo disertace', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dln', 'Kreslíc', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dnc', 'Tanečník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dnr', 'Dárce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dpc', 'Zobrazovaný', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dpt', 'Skladník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('drm', 'Návrhář', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('drt', 'Režisér', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dsr', 'Výtvarník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dst', 'Distributor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dte', 'Dedikant', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dto', 'Dedikátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('dub', 'Domnělý (pochybný) autor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('edt', 'Editor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('egr', 'Rytec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('elt', 'Galvanotypér', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('eng', 'Technik', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('etr', 'Leptař', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('exp', 'Expert', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fac', 'Zhotovitel faksimile', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('flm', 'Střihač', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fmo', 'Dřívější majitel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('fnd', 'Investor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('frg', 'Falzifikátor, padělatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('-grt', 'Grafický technik', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('hnr', 'Poctěná osoba', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('hst', 'Konferenciér', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ill', 'Ilustrátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ilu', 'Iluminátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ins', 'Autor věnování', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('inv', 'Vynálezce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('itr', 'Instrumentalista, hráč na hudební nástroje', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ive', 'Dotazovaný, interviewovaný', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ivr', 'Dotazovatel, interviewující', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lbt', 'Libretista', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lee', 'Obžalovaný v odvolacím řízení (v církevním nebo námořním právu) jako odpůrce odvolatele', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lel', 'Obžalovaný (v církevním nebo námořním právu)', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('len', 'Půjčovatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('let', 'Obžalovaný v odvolacím řízení (v církevním nebo námořním právu) jako odvolávající se strana', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lie', 'Žalobce v odvolacím řízení (v církevním nebo námořním právu) jako odpůrce odvolatele', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lil', 'Žalobce (v církevním nebo námořním právu)', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lit', 'Žalobce v odvolacím řízení (v církevním nebo námořním právu) jako odvolávající se strana', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lsa', 'Zahradní a krajinný architekt', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lse', 'Původní nositel práv, licence', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lso', 'Udělovatel povolení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ltg', 'Litograf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('lyr', 'Textař', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mdc', 'Technik v oblasti metadat', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mod', 'Moderátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mon', 'Dozorčí, kontrolor)', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mrk', 'Editor programovacích jazyků', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mte', 'Kovorytec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('mus', 'Hudebník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('nrt', 'Vypravěč-komentátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('opn', 'Oponent', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('org', 'Původce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('orm', 'Organizátor akce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('oth', 'Jiná role', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('own', 'Vlastník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pat', 'Mecenáš', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pbd', 'Šéfredaktor, odpovědný redaktor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pbl', 'Nakladatel, vydavatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pfr', 'Korektor tištěných materiálů', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pht', 'Fotograf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('plt', 'Výrobce tiskových forem', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pop', 'Tiskař obrazu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ppm', 'Výrobce papíru', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prc', 'Provozní technik', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prd', 'Pracovník produkce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prf', 'Účinkující', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prg', 'Programátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prm', 'Tiskař grafik', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pro', 'Producent, výrobce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('prt', 'Tiskař', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pta', 'Žadatel o udělení patentu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pte', 'Žalobce (v civilních věcech) jako odpůrce odvolatele', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ptf', 'Žalobce (v civilních věcech)', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('pth', 'Majitel patentu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ptt', 'Žalobce (v civilních věcech) jako odvolávající se strana', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rbr', 'Rubrikátor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rce', 'Technik záznamu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rcp', 'Adresát, příjemce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('red', 'Redaktor, výkonný redaktor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ren', 'Projektant architektonických ztvárnění', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('res', 'Výzkumník', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rev', 'Recenzent', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rpt', 'Reportér, zpravodaj', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rpy', 'Odpovědná strana', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rse', 'Zúčastněná osoba v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rsp', 'Zúčastněná osoba', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rst', 'Zúčastněná osoba v odvolacím řízení', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rth', 'Vedoucí výzkumného týmu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('rtm', 'Člen výzkumného týmu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sad', 'Vědecký poradce', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sce', 'Scénárista', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('scr', 'Písař, opisovač', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('scl', 'Sochař', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sec', 'Sekretář, tajemník, jednatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sgn', 'Signatář', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('sng', 'Zpěvák', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('spk', 'Spíkr', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('spn', 'Sponzor', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('srv', 'Geodet, zeměméřič', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stn', 'Vývojový pracovník v oblasti standardizace', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('stl', 'Vypravěč pohádek, anekdot', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('str', 'Stereotypér', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('ths', 'Vedoucí diplomové práce nebo disertace', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('trc', 'Přepisovač', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('trl', 'Překladatel', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tyd', 'Návrhář písma', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('tyg', 'Typograf', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('voc', 'Pěvec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wam', 'Autor textu doprovodného materiálu', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wdc', 'Dřevořezbář', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wde', 'Dřevorytec', 'cs');
INSERT INTO [relator] ([relator_code], [name], [lang]) VALUES ('wit', 'Svědek', 'cs');
